export const events = [
  {
    title: "Next.js Conference 2025",
    image: "/images/event1.png",
    slug: "nextjs-conf-2025",
    location: "San Francisco, CA",
    date: "November 15, 2025",
    time: "9:00 AM PST",
  },
  {
    title: "React Summit Jakarta",
    image: "/images/event2.png",
    slug: "react-summit-jakarta-2025",
    location: "Jakarta Convention Center",
    date: "December 3, 2025",
    time: "10:00 AM WIB",
  },
  {
    title: "TypeScript Global Meetup",
    image: "/images/event3.png",
    slug: "typescript-global-meetup-2025",
    location: "Virtual Event",
    date: "November 28, 2025",
    time: "2:00 PM UTC",
  },
  {
    title: "DevFest Indonesia 2025",
    image: "/images/event4.png",
    slug: "devfest-indonesia-2025",
    location: "ICE BSD City, Tangerang",
    date: "December 9, 2025",
    time: "8:30 AM WIB",
  },
  {
    title: "Web Performance Summit",
    image: "/images/event5.png",
    slug: "web-performance-summit-2025",
    location: "Singapore EXPO",
    date: "January 12, 2026",
    time: "9:00 AM SGT",
  },
  {
    title: "Frontend Developer Days",
    image: "/images/event6.png",
    slug: "frontend-developer-days-2026",
    location: "Bali International Convention Centre",
    date: "January 25, 2026",
    time: "10:00 AM WITA",
  },
];
